version: '2.2'
services:
  fypcujune:
    container_name: fypcujune
    build: .
    command: bash -c "uvicorn main:main --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - '8036:8000'
    restart: always
  celery_workerfypcujune:
    container_name: celery_workerfypcujune
    build: .
    working_dir: /app
    command: celery -A mlcelery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - fypcujune
