version: '2.2'
services:
  u1:
    container_name: u1
    build: .
    command: bash -c "uvicorn main:main --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - '8035:8000'
    restart: always
  celery_workeru1:
    container_name: celery_workeru1
    build: .
    working_dir: /app
    command: celery -A mlcelery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - u1
