version: '2.2'
services:
  u4:
    container_name: u4
    build: .
    command: bash -c "uvicorn main:main --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - '8039:8000'
    restart: always
  celery_workeru4:
    container_name: celery_workeru4
    build: .
    working_dir: /app
    command: celery -A mlcelery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - u4
