version: '2.2'
services:
  u5:
    container_name: u5
    build: .
    command: bash -c "uvicorn main:main --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - '8040:8000'
    restart: always
  celery_workeru5:
    container_name: celery_workeru5
    build: .
    working_dir: /app
    command: celery -A mlcelery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - u5
